# Site settings
title: David Mai, Ph.D.
email: davidmai.macro@gmail.com
url: https://davemai.github.io
description: Postdoc at Fred Hutchinson Cancer Research Center

# API Key for Google Maps
google_maps_javascript_api_key: "AIzaSyCpjWmOIMYcXH6Apz0AiXe2co2A27QTHFs"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: 

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: bluesky
    url: https://bsky.app/profile/davemai.bsky.social
  - title: twitter
    url: https://twitter.com/lococyte
  - title: facebook
    url: https://www.facebook.com/daveymai
  - title: github
    url: https://github.com/davemai
  - title: linkedin
    url: https://www.linkedin.com/in/davemai

# Build settings
markdown: kramdown
permalink: pretty
