# Site settings
title: David Mai
email: davidmai.macro@gmail.com
url: https://davemai.github.io
description: "PhD student in bioengineering at University of Pennsylvania."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: 

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/davemai_
  - title: facebook
    url: https://www.facebook.com/damailperson
  - title: github
    url: https://github.com/davemai

# Build settings
markdown: kramdown
permalink: pretty
